name: collect

on:
  schedule:
    - cron: 12 0 * * *
  repository_dispatch:
    types: [mamual_trigger]

jobs:
  collect:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2.1.0
      with:
        node-version: 10.21.0

    - run: ./.github/scripts/decrypt_secret.sh $FIREBASE_ADMIN_SECRET_PASSPHRASE ./bat/acnh-cddb-firebase-adminsdk.json.gpg
      env:
        FIREBASE_ADMIN_SECRET_PASSPHRASE: ${{ secrets.FIREBASE_ADMIN_SECRET_PASSPHRASE }}

    - env:
        TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        INSTAGRAM_QUERY_HASH: ${{ secrets.INSTAGRAM_QUERY_HASH }}
        ALGOLIA_ID: ${{ secrets.ALGOLIA_ID }}
        ALGOLIA_KEY: ${{ secrets.ALGOLIA_KEY }}
        GCLOUD_PROJECT: acnh-cddb
      run: |
        yarn install
        export GOOGLE_APPLICATION_CREDENTIALS=$HOME/secrets/acnh-cddb-firebase-adminsdk.json
        echo $GOOGLE_APPLICATION_CREDENTIALS
        ls -l $HOME/secrets
        yarn workspace @acnh-cddb/bat collect
